### ISSUE TITLE
[Substance] Unusual behavior with JIDE CheckboxTree component

### ISSUE THREAD

**Issue by wishkres** [kirill-grouchnikov/radiance#114]
### Version of Radiance (current development is 2.0-SNAPSHOT)
1.0.2

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance

### Version of Java (current minimum is 8)
Reproduced with Java 8, 10, and 11

### Version of OS
Reproduced on Windows 10 and CentOS 7

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
When using a Substance L&F with a recent version of JIDE Common Layer (tested in 3.6.18), the JIDE CheckboxTree does not function correctly. The behavior is inconsistent, but some of the idiosyncrasies include checking one box also checking the boxes above it, unchecking a box may select all of the other boxes, and strange behavior where hovering over a checkbox selects or deselects it. 

It behaves normally when used with some older versions (such as JIDE version 2.7.8).

Example demo code attached.

[CheckboxTest.java.txt](https://github.com/kirill-grouchnikov/radiance/files/2729064/CheckboxTest.java.txt)

Using Metal L&F and JIDE 3.6.18 - works
Using Substance L&F and JIDE 3.6.18 - works
Using Substance L&F and JIDE 3.6.18 - CheckboxTree is broken.

**Comment by kirill-grouchnikov** [comment]
For a bit of history, there was a very preliminary attempt at providing Substance UI delegates for JIDE components back in 2008/09. There was very little interest in it at the time, and it was discontinued.

From a very brief glance at the JIDE code that corresponds to 3.6.18 from Maven (Github repository seems to be on 3.7.4), the CheckBoxTree component goes through quite a few loops trying to wrap a "regular" two-state checkbox with a tri-state checkbox in a way that works across multiple look-and-feels. My understanding from all the way back then is that JIDE also had built in support for some of the core look-and-feels (probably not Nimbus) and a couple of third-party ones.

To be honest, I am not looking to spend time on trying to see where things have worked with an earlier version of JIDE and are not working with the later ones. This is probably related to some Substance-specific code paths that I have for check box animations and cached offscreen images to speed up the rendering part. Whatever tricks JIDE does to make the bi-state checkbox turn into a tri-state one are probably not playing well with Substance / Radiance.

My intent with the public APIs is to provide a flexible enough surface for third-party developers - be it component developers or app developers - to render additional components in a way consistent with Substance (visuals as well as animations). However, I do not have resources to track non-Radiance components for such purposes.

This is not ideal, of course, for those developers that do have a mix of non-Radiance components that they do not fully control. I would suggest checking with JIDE to see if they have a publicly-supported way to provide a UI delegate for that component, and to take a look at `SubstanceCheckBoxUI` to see how things are rendered for this specific part (it eventually gets to https://github.com/kirill-grouchnikov/radiance/blob/master/substance/src/main/java/org/pushingpixels/substance/internal/utils/SubstanceImageCreator.java, lines 139-169 and 577-631).

Closing this since I don't have any plans to pursue JIDE support in Radiance.
