### ISSUE TITLE
Several simultaneously playing timelines for the same property of the same object must be coordinated

### ISSUE THREAD

**Issue by gregory-ledenev** [kirill-grouchnikov/radiance#145]
### Version of OS

> That is in the application domain. Interpolating the same property from multiple timelines is not prohibited by Trident and is not coordinated in any way. Such coordination or coalescing is done in the code that is using timelines. For example, going back to StateTransitionTracker - the reason it creates a new timeline on every model change is that you can press a button right after moving the mouse over it. So the button starts as regular - let's say light grey. Then rollover would move it to, let's say yellow. And the press would move it to orange. But you don't want two competing timelines fading the color to yellow and orange at the same time. So what happens is that when the button is pressed, the old timeline (regular -> rollover) is aborted (line 322), and a new timeline interpolates the state from rollover to rollover+pressed. The background is interpolated from whatever partially yellow there was to full orange. If the mouse is moved away during that animation, a new timeline will be created, going from whatever partial orange there was back to light grey of the regular state.

Ouch. That is I was afraid of :(. Well, I can not imagine a scenario when there is a need to animate the same property of the same object to different values in parallel. Even if there are cases when it is needed they are would be a 0.001% minority. So to properly animate ONE simple property one should (just iterating through my own experience):
- realize and understand the problem (experience jerking).
- try to find a solution; no luck.
- contact the author. luckily you are responsive :). 
- get a complex solution for a simple issue that (I believe) should never exist :(.

I hope you would agree that it is not a thing the users would appreciate… Moreover, I see the following issues with that “abort previous timeline” scenario:

1. If that scenario is properly encapsulated to a class - it requires heavy copy-pasting to support several properties or making a helper class to reduce duplicated code.

2. If it is not encapsulated  and implementation is scattered through the code when some properties should be animated - it hardly would work. There’s no easy way to track previous instances of timelines for that approach.

3. This scenario seems does NOT work at all when grouping several animations together. For example, first let's animate the “color” and “current” properties:

```
Timeline timeline1 = new Timeline();
timeline1.addPropertyToInterpolate(“current”, 1, 100);
timeline1.addPropertyToInterpolate(“color”, Color.red, Color.blue);
timeline1.play();
```

Then we need to animate the “current” property alone (while timeline1 is running):

```
timeline1.abort();

Timeline timeline2 = new Timeline();
timeline2.addPropertyToInterpolate(“current”, obj.getCurrent(), 100); // get intermediate value for “current"
timeline2.play();
```

As result the “color” property will stop on some intermediate value between red and blue! Either I’m missing something or this approach will fail frequently.

I hope you see the problem and would agree that it should be resolved on the framework level. It should be just “fire and forget”… So the users should simply write (as per documentation):

```
Timeline timeline1 = new Timeline();
timeline1.addPropertyToInterpolate(“current”, 1, 100);
timeline1.addPropertyToInterpolate(“color”, Color.red, Color.blue);
timeline1.play();
```

and do not care about jerking, other timelines whatever. It should just work keeping, simple things, well simple :).

**Comment by kirill-grouchnikov** [comment]
I do not follow the scenario here. You're saying that you start the timeline by animating two properties, _current_ to 100 and _color_ to blue. And then in the middle of it you want to animate _current_ to 100 again? 

Maybe you meant that in the middle of it you want to animate _current_ to 200 instead, and continue animating _color_ to blue? That is not a well-defined scenario though. What if the original animation is 99% done? If the timeline duration is set to, let's say, 1000ms and there's only 10ms left, does that mean that _current_ jumps from 99 to 200 over those 10ms? Or does the timeline automatically reset how long it should be running? If so, that doesn't seem to be right for those properties that are almost done being interpolated. And the same questions apply to the interpolator.

Finally, there's the assumption that property getter and setter are the same for the same property name in _TimelinePropertyBuilder_. That is not enforced in any way by Trident.

For more realistic scenarios of animating the same property from A to B, and then needing to go to C instead in the middle of it, see https://www.pushing-pixels.org/2010/01/05/animations-102-changing-direction.html. That's just one example of domain-specific decisions that need to be made far above the layer where Trident operates. Different domains would have different rules on how such "change" in animation should be handled. Those might be helper utilities that are built on top of Trident, or maybe code that is spread across the application codebase. 

Perhaps I'm misreading the specific scenario you're talking about. If you can tweak the code in your sample to reflect what it is that you want to do on the application side when one of the animated properties needs to change its target, along with the specific expectations what happens to the other properties and how timeline duration + property interpolator + property setter aspects are being handled (automatically?), that would be great. Otherwise all of this does not belong at the Trident level.

**Comment by gregory-ledenev** [comment]
> I do not follow the scenario here. You're saying that you start the timeline by animating two properties, _current_ to 100 and _color_ to blue. And then in the middle of it you want to animate _current_ to 100 again?

Yes, it is no so correct example. Correct one would be from 100 to 75. Anyway, even repetitive animation from 1 to 100 is legit one for the purpose of this demonstration. Correct result of the second transaction must be current=100 (75 after correction) and color=blue. Though that code produces color between red and blue. And see no way how to avoid this.

> For more realistic scenarios of animating the same property from A to B, and then needing to go to C instead in the middle of it...

I am talking about simple scenario that spans 99.99% of use-cases. No one basically cares about how the current value gets its final figure. It should go from 1 to 75 flawlessly without jerking. So it may stop on 25 and then go to 75. Or it may grow to 90 and shrink to 75 depending of the timing. This logic doesn't belong to app domain in general. It s like sin() function calculation should be up to particular application :). Anyway the only approach that partially works is aborting prev. timeline that stops the prev. timeline whenever it is without easing and then starts the second one from the scratch. It is not flawless in the perfect world but it is way better than jerking.

> Perhaps I'm misreading the specific scenario you're talking about...

Ok, let me be clear. My interest neither is an academic one. Nor it is "I want to be a part of some fancy open source development" :). We are building enterprise-grade applications that require a kind of gauge component. So we decided to build it ourselves. Sample screenshot is below:
https://www.dropbox.com/s/u7rb0cue8qauahi/gauges.png?dl=0
Naturally, that gauge is a good example of those components that should be animated. I've seen Trident library like 10 years ago :) and decided to gave it a try. 

So that gauge basically has like 10 animatable properties: colors, current, max, range etc. All the props. are either Color or double. Nothing complicated there in the scope of animation. No layout change, no influence to other components. Just self contained component. Gauge can be easily updated several times per second to reflect changes. That update may alter anything. Current color maybe changed to orange if current value reaches 75% of the range etc. Certainly all that changes should be grouped to avoid redundant updates. So there can be easily several timelines running simultaneously which produces jerking. Nothing unique there though. Even in your components you experienced that (rollover, pressed color scenario). Let me guess how may times you copy pasted your code to different places to achieve result that must be produced automatically by framework even without thinking of it. 

I've spent last 4 years building very complex apps for iOS and I do not remember caring about jerking in general cases. It just works. I believe that Android goes that way. Otherwise is too complicated for the users to enjoy animations. It is better not to use animations at all than to deal with such complexity to achieve simple results. That's is why I think that timelines coordination must be done on the framework level, especially keeping in mind that it can NOT be done by end users at all. 

So I would like to repeat myself - my sample with two transactions that should simply work:

```
Timeline timeline1 = new Timeline();
timeline1.addPropertyToInterpolate(“current”, 1, 100);
timeline1.addPropertyToInterpolate(“color”, Color.red, Color.blue);
timeline1.play();

Timeline timeline2 = new Timeline();
timeline2.addPropertyToInterpolate(“current”, 100, 75);
timeline2.play();
```
So results must be current=75 and color=blue without jerking and any additional code. It should just work keeping, simple things, well simple :). In your rollover/pressed scenario it should be just calls of setColor(...) that looks like:

```
public void setColor(Color aColor) {
    Timeline timeline = new Timeline();
    timeline.addPropertyToInterpolate(“color”, getColor(), aColor);
    timeline.play();
}
```
everything else must be handled on framework level.

**Comment by kirill-grouchnikov** [comment]
```java
Timeline timeline1 = new Timeline();
timeline1.addPropertyToInterpolate(“current”, 1, 100);
timeline1.addPropertyToInterpolate(“color”, Color.red, Color.blue);
timeline1.play();

Timeline timeline2 = new Timeline();
timeline2.addPropertyToInterpolate(“current”, 100, 75);
timeline2.play();
```

How is that reconciled? Does the second timeline "win" (by winning I mean `current` ending up at 75) just because it started to play after the first timeline? What if the first timeline is configured with a longer duration and it is still playing even after the second timeline is done? And I'm not even talking about custom property setters where two timelines that are interpolating the same property (by name) are not guaranteed to be working on the same backing object field.

It is exactly this point in the middle where the app says "oh wait, forget part of what you were doing with the first animation, and now bring this one property to a different target value". My feeling is that it belongs firmly in the application domain, or a layer above Trident. Semantics are very important here. You have to be very specific about the behavior of N timelines, each one animating different set of properties, and every property that can be animated by any subset of those timelines. Which animation "wins" for each such property (the one that started playing last, or the one that ends playing last)? What happens at each inflection point to prevent jitter / jerking? 

Substance has a few utility classes that are exactly that layer of abstraction above Trident primitives. `StateTransitionTracker` is one of them - where the logic in that layer is exactly what I want to happen for the particular animations in Substance. That logic is not universal by any means. See the above-linked https://www.pushing-pixels.org/2010/01/05/animations-102-changing-direction.html where translating timeline position to vehicle coordinates is done based on the physical limitations of moving vehicles.

**Comment by gregory-ledenev** [comment]
> How is that reconciled? Does the second timeline "win" (by winning I mean `current` ending up at 75) just because it started to play after the first timeline? 

Yes, definitely! It is like "what a value "current" gets after executing the code?"

```
setCurrent(100);
setCurrent(75);
```
It's 75. Isn't it? Animation, should not change a thing if possible.  Certainly, it can but it should not at least in that simple case.

> What if the first timeline is configured with a longer duration and it is still playing even after the second timeline is done? 

First (not so important), 99.99% of cases timeline durations are the same and never configured.

**Second (very important)**, I'm ***STRICTLY*** against timelines simultaneously changing the same property of the same object. It is the root of the problem. And it is very bad from any point of view. 

So in my example, as soon as timeline2 starts playing (assuming timeline1 is still playing):
1. the "current" property must be excluded from playing
2. timeline2 must change the "from" value for the "current" property to be the last value calculated by timeline1

Hmmm... Sounds, familiar. Isn't it? It the same approach you used in your rollover/pressed example!  I believe you did it many times across all your code! Do you think copy-pasting is the right thing to do? Do you like produce redundant and badly readable and maintainable code? I suppose you don't.

So the general rule must be: **There can be just ONE playing interpolation of certain property of certain object.**

Following that rule solves everything.

**Comment by kirill-grouchnikov** [comment]
This would require changing pretty much the entire surface of Trident. If your expectation is that starting a timeline has to automatically exclude all its properties from all other active timelines, and then clear the properties when the timeline is done, you're looking for some kind of a singleton object that operates at the level of object+property. 

Some kind of an API that orchestrates and excludes properties, removes them when they're done, etc. That is simply not going to happen in Trident. 

And let's refrain from personal attacks on code that I may or may not have written in Radiance over the years if you want to have a civil conversation.

**Comment by gregory-ledenev** [comment]
OK. Got it. Missing orchestration is a show-stopper to me. Thank you for conversation and good luck in your development.

BTW: I was not attacking your code I was trying to convince you that the same code that repeats from class to class needs attention and its reuse should be addressed in the framework.
