### ISSUE TITLE
Pasting unicode emoji to a text component makes component lose AA

### ISSUE THREAD

**Issue by tropicaldev** [kirill-grouchnikov/radiance#179]
using:
- radiance 1.0.2  (version compatible with java 8)
- Java 1.8u192
- Win 10

When pasting text that has unicode chars like emojis to a text component, that component loses anti-aliasing.

Setting to system look and feel the text component don't lose anti-aliasing.

**Comment by DanielWebelsiep** [comment]
I think it is the same problem like https://github.com/kirill-grouchnikov/radiance/issues/178. The AntiAliasing font settings in Neon does not work correctly. All standard L&Fs stores the font AA settings in the _UIManager.getDefaults()_ table. In Radiance the font AA settings are only set by NeonCortex class during rendering. 

For example the MetalLookAndFeel and WindowsLookupAndFeel calling _SwingUtilities2.putAATextInfo(lafCond, table)_ in _initComponentDefaults(UIDefaults table)_ method to initialize the font AA settings. The SubstanceLookAndFeel does not do that, because StringUtilities2 is private since java 9. But the AA settings from the UIManager.getDefault(RenederingHint.KEY_TEXT_ANTIALIASING) are used to initialize the font metrics and font rendering. In NeonContex class only the GraphicsConfiguration is modified with desktop hints, so rendering works most times. But the font metrics for the text cursor are running without AA settings so the pixel position is wrong, The component size is also calculated without AA. Then starting the application the FontStrikeDescription is created without AA and cached in the private Strike cache. If a breakpoint is set into sun.font.FontStrikeDesc.getAAHintIntVal(Font2D, Font, FontRenderContext) it can be analysed. The AntiAliasing hint is always OFF with SubstanceLookAndFeel. I modified SubstanceLookupAndFeel and copy code from SwingUtilities2 to fix problem #178.


    protected void initComponentDefaults(UIDefaults table) {
        SubstanceCortex.GlobalScope.initFontDefaults(table);
        this.skin.addCustomEntriesToTable(table);
        Toolkit toolkit = Toolkit.getDefaultToolkit();
		Map<Object, Object> desktopHints = (Map<Object, Object>) toolkit.getDesktopProperty("awt.font.desktophints");

        Object aaHint = desktopHints.get(RenderingHints.KEY_TEXT_ANTIALIASING);
        if (aaHint == null
                || aaHint == RenderingHints.VALUE_TEXT_ANTIALIAS_OFF
                || aaHint == RenderingHints.VALUE_TEXT_ANTIALIAS_DEFAULT) 
		{
            // do nothing
        }
		else
		{
            table.put(RenderingHints.KEY_TEXT_ANTIALIASING, aaHint);
            table.put(RenderingHints.KEY_TEXT_LCD_CONTRAST, desktopHints.get(RenderingHints.KEY_TEXT_LCD_CONTRAST));
        }		
    }

**Comment by tropicaldev** [comment]
I tested with the suggested fix but the problem persists.

Note that i had to include the initial super.initComponentDefaults(table) or else an exception is thrown because some components needs to have some defaults (like Jtree indents ) when instanciated.

DanielWebelsiep, I assume you are not experiencing the same problem when pasting an emoji to a textcomponent...what's your Radiance and Java versions?

**Comment by kirill-grouchnikov** [comment]
I'll add the code from Daniel in 2.5-SNAPSHOT tonight. I can't comment on whether this might fix it for older Radiance releases. 

It's definitely not something that is part of the "official" anti-aliasing documentation at https://docs.oracle.com/javase/9/docs/api/java/awt/doc-files/DesktopProperties.html. Not sure what's the "official" source for JDK classes these days. The fix proposed above relies on what https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.desktop/share/classes/sun/swing/SwingUtilities2.java is doing in OpenJDK 11. That seems to be different from https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/sun/swing/SwingUtilities2.java, so that fix might not indeed work on earlier versions of Java.

And for that matter, it might not work on any version - since this is all undocumented and relying on the particular implementation details. From my point of view, this should really be populated by BasicLookAndFeel and not by "leaf" core look-and-feel classes, as that would effectively provide correct support for third-party look-and-feels.

**Comment by tropicaldev** [comment]
i just looked at java 8 laf srcs...

To work in radiance 1.0.2 with java 8 the fix needs to be:

    protected void initComponentDefaults(UIDefaults table) {
        
        super.initComponentDefaults(table);
        SubstanceCortex.GlobalScope.initFontDefaults(table);
        this.skin.addCustomEntriesToTable(table);

        //fix
        //https://github.com/kirill-grouchnikov/radiance/issues/179
        Object aaTextInfo = SwingUtilities2.AATextInfo.getAATextInfo(true);
        table.put(SwingUtilities2.AA_TEXT_PROPERTY_KEY, aaTextInfo);  

    }

no change to have the fix  in the latest version of radiance that suports java 8?

**Comment by kirill-grouchnikov** [comment]
Both 2.0 and 2.5-SNAPSHOT require Java 9 as the minimum.

**Comment by DanielWebelsiep** [comment]
We migrate from Java 8 to Java 11 for our upcoming release. To test the fix I used Adopt OpenJDK 11.0.3+7 and the Radiance 2.0.1 source code. The changes on java 9 to support high dpi displayes with http://openjdk.java.net/jeps/263 should explain the code differences.

**Comment by kirill-grouchnikov** [comment]
This particular one is not about high dpi displays. It is about platform-consistent text antialiasing that has been available since Java 6 - https://docs.oracle.com/javase/6/docs/api/java/awt/doc-files/DesktopProperties.html

However, this specific area has not exposed any additional APIs that third-party look-and-feel providers need to maintain consistent text rendering (antialiasing, current desktop font family, style and size, etc). So there's a lot of hacks in Substance to try and maintain that consistency (that is missing, afaict from Metal and Nimbus). These are hacks because they rely on something that is, unfortunately, semi-private undocumented implementation details.

**Comment by DanielWebelsiep** [comment]
I could verify the bugfix and also #179 with java 11 on windows 10 with Radiance 2.5-SNAPSHOT. I had to change the standard font to Sansserif under Window to support our Unicode test String.
"mmm Text ß€äüöÄÜÖ  čšžČŠŽ Пасха это は区理知の 😉 😊 😋 😎 AA"
