### ISSUE TITLE
Linux Resizing

### ISSUE THREAD

**Issue by JacobRhiel** [kirill-grouchnikov/radiance#204]
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

NW, SW, North and West resizing (anything involving changing the x,y of the application bounds) will not be accurate with a lag, whenever you drag itll randomly move the applications x,y towards the direction you're dragging almost is if you are pushing it with your mouse instead of resizing. It only does it for the mentioned directions the others work fine.

**Comment by kirill-grouchnikov** [comment]
Does it happen under Metal (in decorated mode) as well, or only under Substance?

**Comment by JacobRhiel** [comment]
Yes it also does it under Metal, the only time it doesn't is if I use the system LaF

**Comment by kirill-grouchnikov** [comment]
Yeah, this is a known issue with resizing decorated windows in Swing. There are a couple of places that talk about it in https://github.com/mgarin/weblaf/wiki/Window-decoration (closer to the end) for WebLaf. 

There's a little bit that can be done with `Toolkit.getToolkit().setDynamicLayout(true)` and `System.setProperty("sun.awt.noerasebackground", "true")`, but otherwise this is pretty much out of reach for custom look-and-feels (or for Metal, in the core case).

This needs to be reported at https://bugs.openjdk.java.net/secure/Dashboard.jspa to be fixed at the JDK level.
