### ISSUE TITLE
[Flamingo] Keyboard focus traversal skips the ribbon application content

### ISSUE THREAD

**Issue by ondrusm** [kirill-grouchnikov/radiance#235]
### Version of Radiance (current development is 3.0-SNAPSHOT) 
3.0 Diamond
### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo
### Version of Java (current minimum is 9)
13
### Version of OS
Windows 7
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
I'm having trouble using the keyboard to traverse controls on my form (Flamingo based application). 
![TestApp](https://user-images.githubusercontent.com/50991381/73160062-4b693d80-40e8-11ea-94dd-780910f8f0e2.png)
When I press the tab key in a text box with label **First** , the focus does not jump to the next text box (with label **Second**), but jumps to the ribbon menu and then remains in menu (never returns back to form)

**Comment by kirill-grouchnikov** [comment]
Added global focus tracking to the main ribbon demo. Looks like the focus traversal only traverses the ribbon content, and completely skips the application "area".

**Comment by kirill-grouchnikov** [comment]
Just getting started to analyze this. The default focus traversal policy is `java.awt.DefaultFocusTraversalPolicy` that extends `java.awt.ContainerOrderFocusTraversalPolicy`.

When `TAB` is pressed, Swing calls to https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/awt/ContainerOrderFocusTraversalPolicy.java#L210 which eventually gets (correctly) to https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/awt/ContainerOrderFocusTraversalPolicy.java#L275 which starts looping over components right after the current focus to find the next one. It calls `accept` to check whether the next candidate is the "right" one.

The logic is in https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/awt/DefaultFocusTraversalPolicy.java#L96 and more specifically in https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/awt/DefaultFocusTraversalPolicy.java#L121. It's not just that the component needs to be focusable. It also needs to be explicitly marked as focusable by the application code (so that `isFocusTraversableOverridden` returns true).

Flamingo marks all its components as focusable out of the box, and this is why the focus traversal works on the ribbon content.

I'm going to check what is the default policy for focus traversal on simple, non-ribbon Swing content to see how it works there.

**Comment by kirill-grouchnikov** [comment]
Hmm, for the main Substance demo, the default focus traversal policy is `LayoutFocusTraversalPolicy` and not `DefaultFocusTraversalPolicy`. Going to take a look at why it's different for `JFrame` and `JRibbonFrame`.

**Comment by kirill-grouchnikov** [comment]
OK, so `KeyboardFocusManager` has `defaultPolicy` which is initialized to `DefaultFocusTraversalPolicy`. Then, during the `JRootPane` initialization, it gets to `UIManager.maybeInitializeFocusPolicy` which sets the default to `LayoutFocusTraversalPolicy` and then that gets set on the frame.

`JRibbonFrame` and its `JRibbonRootPane` short-circuit some of that logic. `JRootPane.updateUI` gets the UI delegate from `UIManager.getUI` call. As a side effect of that call, the default focus traversal policy is set (as above) to `LayoutFocusTraversalPolicy`. This is a completely-WTF side-effect of getting the UI delegate.

`JRibbonRootPane.updateUI` just creates an instance of `SubstanceRibbonRootPaneUI` directly.

I'm going to explicitly call 

```java
        KeyboardFocusManager.getCurrentKeyboardFocusManager().
                setDefaultFocusTraversalPolicy(new LayoutFocusTraversalPolicy());
```

in the constructor of `JRibbonRootPane` to re-create the side effect of the `JRootPane` initialization. That also fixes the rather random order of traversing the ribbon content that Flamingo had before. 

Fix will be submitted in the next day or two.

**Comment by kirill-grouchnikov** [comment]
As a temporary workaround for 2.5.1, you can do the same call in your app:

```java
        KeyboardFocusManager.getCurrentKeyboardFocusManager().
                setDefaultFocusTraversalPolicy(new LayoutFocusTraversalPolicy());
```

probably before creating your `JRibbonFrame`
