### ISSUE TITLE
[Photon] "java: code too large"

### ISSUE THREAD

**Issue by simon04** [kirill-grouchnikov/radiance#250]
### Version of Radiance (current development is 3.0-SNAPSHOT)
3.0-SNAPSHOT // 42d17c7

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Photon

### Version of Java (current minimum is 9)
Java 11

```
$ gradle --version
Gradle 6.2.2
Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.6 (Oracle Corporation 11.0.6+10)
OS:           Linux 5.5.10-arch1-1 amd64
```

### Version of OS
Arch Linux

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
Running SvgTranscoder on https://commons.wikimedia.org/wiki/File:Openstreetmap_logo.svg results in a huge Java file which cannot be compiled due to "java: code too large".

Here is the resulting Java file: [img_Openstreetmap_logo.java](https://github.com/kirill-grouchnikov/radiance/files/4365382/img_Openstreetmap_logo.java.txt)

Ideally, Photon would split the generated code into smaller classes. As a user, I'd like to know which transcoded files will/may cause a problem (check resulting file size and report a warning?).

**Comment by kirill-grouchnikov** [comment]
That one fails for me with this exception:

```
Mar 23, 2020 11:29:33 AM org.pushingpixels.photon.api.transcoder.SvgTranscoder transcode
SEVERE: null
java.io.IOException: Root element namespace does not match that requested:
Requested: http://www.w3.org/2000/svg
Found: null
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:377)
	at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:202)
	at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createSVGDocument(SAXSVGDocumentFactory.java:124)
	at org.apache.batik.bridge.DocumentLoader.loadDocument(DocumentLoader.java:106)
	at org.pushingpixels.photon.api.transcoder.SvgTranscoder.transcode(SvgTranscoder.java:84)
```

**Comment by kirill-grouchnikov** [comment]
I do see it with https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg though.

The generated `innerPaint` is over 12,000 lines. There's a lot of tiny elements there, six levels deep - as can be seen from the marker comments like `_0_2_2_4_6_11`. 

One possible way would be to keep track of how many lines are produced into the `paintingCodeStream` and split them into multiple methods / functions to be emitted as the `TOKEN_PAINTING_CODE` content. Doesn't have to be pretty, as this is generated code in any case. Maybe every 1000 lines would mark a start of a new method, much like with base64-encoded raster content.

**Comment by kirill-grouchnikov** [comment]
With this CL, the structure of the generated painting code is a bit different. It is split into chunks of roughly 1000 lines of separate `_paint` methods. See https://github.com/kirill-grouchnikov/radiance/blob/master/demos/flamingo-demo/src/main/java/org/pushingpixels/demo/flamingo/svg/bigflag/Flag_of_Spain.java and roughly 12000 lines of Java2D instructions that are called in lines 12461-12472.

With this, a 59KB original file (from https://en.wikipedia.org/wiki/File:Flag_of_Spain.svg) is transcoded to a 643KB Java file, and then compiled to a 319KB class file.

This is not a complete solution to arbitrarily complex SVG content like https://en.wikipedia.org/wiki/File:Flag_of_Ecuador.svg that has a lot more details or https://en.wikipedia.org/wiki/File:Flag_of_Afghanistan.svg that has a huge path with more than 8K elements in it (all the white outlines of mosque, wheat and inscription is a single path). Such files produce a Java / Kotlin class that can't be compiled due to too many symbols in it.

I do not have plans to provide further support for such huge SVG files. That is well beyond the intended usage and the scope of Photon - convert reasonably sized **icons** for usages as supporting imagery, and not arbitrarily complex content. At some point, the binary size of the compiled transcoded classes is at the same order of magnitude as simply bundling the original SVGs and the full Batik distribution.

There will be an additional small change tomorrow before this issue will be closed.

**Comment by IvanRF** [comment]
For this issue that is related to Java file size, maybe it will help to use smaller variable names when you implement the solution for #253 . I mean, you could use `gp` or `p` instead of `generalPath` and this will reduce the number of cases where a "java: code too large" error is reached.

**Comment by kirill-grouchnikov** [comment]
That is an unsubstantiated assertion. Large methods / classes run into the 65K entry limitations in symbol tables available in the bytecode class format.

**Comment by IvanRF** [comment]
You're right, I mixed things, I thought the error was thrown creating the Java file.

**Comment by kirill-grouchnikov** [comment]
Also, at the very top of https://github.com/kirill-grouchnikov/radiance/blob/master/docs/photon/photon.md

_The_ goal of this project is to enable usage of vector-based **icons** in Swing applications._

Photon does not aim to support arbitrarily complex SVG content.

**Comment by simon04** [comment]
One (big?) disadvantage of https://github.com/kirill-grouchnikov/radiance/commit/a86f9734cea6364d8c12cb82679946a3f2ee24fc is that now every transcoded images has a bunch of fields. Those require additional space on the heap. The very `transformsStack` requires 88 bytes.

```java
public class XXX implements ResizableIcon {
    private Shape shape = null;
    private Paint paint = null;
    private Stroke stroke = null;
    private Shape clip = null;
    private Stack<AffineTransform> transformsStack = new Stack<>();
// ...
```

**Comment by kirill-grouchnikov** [comment]
There's going to be penalties for any implementation of this. It can be one method that allocates variables on the stack during every drawing pass, or class-level variables like these. We're talking about desktop applications here, and to be honest, 100 bytes for even 100 icons is extra 10KB on the heap. That's nothing.

As with Substance, I'm more interested in improving how fast these icons are rendered.

**Comment by kirill-grouchnikov** [comment]
Other possible approaches are passing the rendering "state" (as parameters) across these split methods. That's going to be either on the stack or on the heap.

One possible optimization would be to use local variables in the case of a single `_paint()` method and only use class fields for the split rendering. That is, however, another unsubstantiated assertion.

It's either static memory allocation, or dynamic memory allocation with associated GC overhead. Unless you can provide a reproducible benchmark that shows measurable memory and rendering time savings for a specific approach, these are all guesses.

**Comment by simon04** [comment]
Likely more critical, `#paintIcon` is no longer thread-safe (as a consequence of a86f973).

**Comment by kirill-grouchnikov** [comment]
It was never thread-safe. These classes are meant to be used in UI. Everything that is on screen is painted from the same UI thread. If you need more than one instance of the "same" icon, use the static `of` method that is generated for all resizable icons.
