### ISSUE TITLE
[Substance] Maximizing bug when using undecorated frame

### ISSUE THREAD

**Issue by Owain94** [kirill-grouchnikov/radiance#284]
### Version of Radiance (current development is 3.5-SNAPSHOT)
3.0.0 and 3.5-SNAPSHOT
### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance
### Version of Java (current minimum is 9)
Java 11.0.4
### Version of OS
Windows 10
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

Ever since updating from 2.5.1 to version 3.0.0 or higher i have a bug with my frame maximizing.

I'm using an undecorated frame with a custom substance title pane, ever since upgrading to version 3+ when i click the maximize button the frame will maximize to full screen and cover the windows taskbar. Previously it would not cover the windows taskbar.

**Comment by kirill-grouchnikov** [comment]
Maybe related to the fix for https://github.com/kirill-grouchnikov/radiance/issues/3 but as I can remember, I did test it on my Windows machine and the maximized app didn't cover the taskbar. Will need to take a look at this to see if there was some other code that went in afterwards.

**Comment by kirill-grouchnikov** [comment]
One question before that though - in the Substance test app, the same behavior is seen under the core Metal look-and-feel. Can you attach a sample app that shows the behavior you're seeing so that I know if I'm looking at the right combination of settings?

**Comment by Owain94** [comment]
Hey @kirill-grouchnikov,

I did a bunch more testing and it happens on all the substance demos in this project, i'm not sure why it happens however.
When i revert the commit you linked it wont maximize over the taskbar anymore, but it'll have issues with multiple scaling settings again.

**Comment by kirill-grouchnikov** [comment]
Does this happen for you under Metal - the core look-and-feel that supports undecorated frames?

**Comment by Nopalin** [comment]
I think it has nothing to do with substance, tracking down the calls when i click maximize button, swing itself uses _GraphicsConfigurations_ obtained with _GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration()_ for setting the size of the frame, but the bounds of that object is all the screen (including taskbar).

I made a workaround by setting the maximizedBounds of the Frame object, considering the task bar area using the default Toolkit.

```
GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();
Insets insets = Toolkit.getDefaultToolkit().getScreenInsets(gc);
Rectangle bounds = gc.getBounds();
bounds.x += insets.left;
bounds.y += insets.top;
bounds.width -= (insets.left + insets.right);
bounds.height -= (insets.top + insets.bottom);
gui.setMaximizedBounds(bounds);
```
Take a note that this works because i have just one screen. Hope this can help someone.

**Comment by ed-erwin-tf** [comment]
HI,

I'm seeing some bugs with resizing (on Windows 10).  I've done a bunch of tests with screens set to various scalings.  I can report the results of these tests, but not sure whether I should use a new bug report, or attach to this one, or to #3 

My tests are with radiance 6.0.1 and 6.5, so maybe not relevant to #3 
My tests use a decorated frame, so maybe not relevant to this issue.  (Undecorated frames work properly for me in 6.5 with corretto 11.)

(I understand this is hard to debug because there are so many possible screen settings in the world, but my test results might help.  Where should I put them?  6.0.1 behaves similar to what is described here.  6.5 is more complicated.)

**Comment by kirill-grouchnikov** [comment]
If it only happens for you with decorated frames (to clarify, these would have the title bar and the window borders provided by the OS), I'd like to have that tracked in a separate bug entry. With as much detail as you can share, ideally also with comparison on how those scenarios behave under core look and feels like Nimbus or Windows.

**Comment by ed-erwin-tf** [comment]
Sure, I'll do that.  Short story: something changed between Radiance 5 and 6 for decorated frames.  For undecorated frames, with windows 11, all LAFs are behaving correctly.  For decorated frames, Radiance 5 ignores (and thus covers) the taskbar (small problem); but Radiance 6+ applies an incorrect scaling factor and can move the window to a different screen.

Thus, for my project, I (reluctantly) use undecorated frames.

**Comment by kirill-grouchnikov** [comment]
That would probably be https://github.com/kirill-grouchnikov/radiance/issues/379

**Comment by kirill-grouchnikov** [comment]
Please file a separate bug. From what I see in https://github.com/kirill-grouchnikov/radiance/commit/97e9bb7f7432561e467d598811888f036857d7c4 that new logic would only be applicable for undecorated frames where Radiance is in charge of running that `MaximizeAction`.

**Comment by kirill-grouchnikov** [comment]
Closing this one. See https://github.com/kirill-grouchnikov/radiance/issues/443 and more specifically, https://github.com/kirill-grouchnikov/radiance/issues/443#issuecomment-1422989635 on why this cannot be reliably addressed at the look-and-feel level.
