### ISSUE TITLE
SubstanceCoreUtilities AWT listeners

### ISSUE THREAD

**Issue by gLuEcKsKrAuT** [kirill-grouchnikov/radiance#285]
### Version of Radiance (current development is 3.5-SNAPSHOT)
3.5-SNAPSHOT
### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance
### Version of Java (current minimum is 9)
9
### Version of OS
win 10
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
internal awt listeners of SubstanceCoreUtilities grow constantly to the brim,
this is maybe also a candidate for weak listeners (ref. #283).

it seems that references from BasicPopupPanelUI is always the same, but added constantly.
can be reproduced with resizing the BasicCheckRibbon from max to min width.
![ui_refs](https://user-images.githubusercontent.com/43807827/84605694-90c3b700-ae9f-11ea-80db-955c74196a60.png)

JRibbonFrame reference seems to prevent the frame from garbage collection.
tested it with [FrameDisposeTest.zip](https://github.com/kirill-grouchnikov/radiance/files/4777296/FrameDisposeTest.zip)

**Comment by kirill-grouchnikov** [comment]
I'm not quite sure what the code is doing there. In `BasicCheckRibbon` there's a call to `setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE)` and that gets respected - when the close button is clicked, the VM exits. 

I see you call `.dispose()` explicitly, but the Javadocs of that method only talks about the underlying implementation releasing the native OS resources and marking the frame as undisplayable - and subsequent calls to `.pack()` or `.show()` will rebuild all the references.

`JRibbonFrame` registers an `AWTListener` in its constructor. I guess I can move that out to a method that gets called in `.pack()` and both variants of `.show()` and unregister it in `.dispose()`. The question is whether that is even worth it - given the target usage of `JRibbonFrame` as the main entry point into the application UI that is using the ribbon component.

As to the `BasicPopupPanelUI` leakage, that will be fixed by explicit checks in `SubstanceCoreUtilities.registerAWTEventListener` to not add the same listener that is already in the list.

**Comment by gLuEcKsKrAuT** [comment]
first of all, thx for the 90982190019610c38c3be0a74b09d17605021a26 duplicate fix.

i reworked the example, i hope this is a bit more clearer and usable [FrameDisposeTest.zip](https://github.com/kirill-grouchnikov/radiance/files/4779318/FrameDisposeTest.zip).
now it uses ```WindowConstants.DISPOSE_ON_CLOSE``` and exits correctly unless of the 
count of not ```gc```ed frames.

basically this should simultate creating a new frame and expect that the previous one
will be ```gc```ed, this works for a ```JFrame```, not for a ```JRibbonFrame```.

i think it will be a good move to let the frame being ```gc```ed. 
if there is a application that combines functionality of e.g. word, excel & powerpoint 
but not want to disable always 60% (or more) of the ribbon content when only 1 aspect is handled. 
then it's necessary to create a new ```JRibbonFrame``` with only relevant ribbon tasks, 
because a task can't be removed dynamically.

apart from the application design, i think to hold hard references 
on already disposed frames isn't useful.

**Comment by kirill-grouchnikov** [comment]
Ribbon frame leaks on listeners (`AWTListener` as well as key tip manager listener) should be addressed now.

**Comment by gLuEcKsKrAuT** [comment]
thats true, not recognized this other static anchor for listeners.
with fab5309d6eb0dc8d1251bc54b989ea8958fb1483 the dispose example works as expected,
thx for the fixes.

**Comment by kirill-grouchnikov** [comment]
Thanks for taking the time to report these leaks!
