### ISSUE TITLE
Beveled Border on Jbutton

### ISSUE THREAD

**Issue by DustinMerrell** [kirill-grouchnikov/radiance#351]
### Version of OS Windows 10 and Mac 11.4

I am unable to get a beveled border to paint on a Jbutton. Is there any documentation on this that I could be missing?

**Comment by kirill-grouchnikov** [comment]
How does your code look like? What are the visuals you're aiming to achieve?

**Comment by DustinMerrell** [comment]
I want to have some sort of border or color change based on the user selection. I am looking to change the hue of the buttons or the border color of the buttons to the user defined color.

 

  void setColor(Color color) {

    if (this.color==color) return;

    this.color = color;

//    if (py3d.crew.Decorator.usingLowUI())

      this.setColor(color);

      this.setOpaque(true);

      setBackgrounds(null, color);

//    if (color == null)

//      setBorder(originalBorder);

//    else{

//      setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED, color, color));

//      setBackgrounds(null, color);

//    }

    setBorder((color==null) ? originalBorder : BorderFactory.createBevelBorder(BevelBorder.RAISED, color, color));

  }

 

 

Thank you

Dustin Merrell

Application Systems Director

 

Pyware Customer Support

Phone - 940-240-8536

Fax - 940-464-0573

 

Chat with me -  <https://drift.me/pywaredustin> https://drift.me/pywaredustin

 

 <http://www.facebook.com/Pygraphics> www.facebook.com/Pygraphics

Facebook Pyware Users Group

 <https://www.facebook.com/groups/377417402308160/> https://www.facebook.com/groups/377417402308160/

**Comment by kirill-grouchnikov** [comment]
Using `BorderFactory.createBevelBorder` directly is not supported, for the simple reason that it doesn't play well with Substance visuals. Since it's still a bit vague in the description, I'll link to a few options:
1. Using a custom [border painter](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/substance/painters/border.md) in a custom skin that provides the option to define your own border visuals. Note the skin's border painter is used across different components, the `JComponent` that you get is not guaranteed to always be a button
2. Using a custom [color scheme bundle](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/substance/skins/colorschemebundles.md) with a color scheme registered for `BORDER` [color scheme association kind](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/substance/skins/colorschemeassociationkinds.md) and one of the selected component states - if that is what you mean by "user selection"
3. Calling `JComponent.setBackground` along with `SubstanceCortex.GlobalScope.setColorizationFactor` API to control application-specific background color that is mixed into the current skin
