### ISSUE TITLE
[Substance] Writing Japanese text fails when using Substance

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#4]
When i use the default system look & feel, and click Browse to select a file i select a file with a Japanese name and its Japanese name appears fine in the JTextField. If i use a Substance look and feel, select the same file, its name appears as blocks in the JTextField.

**Comment by enwired** [comment]
I am able to get around this on Windows by using 
`SubstanceCortex.GlobalScope.setFontPolicy(fontPolicy)`
with a `FontPolicy` object designed to return fonts based on `Arial Unicode MS` font.

But if you are thinking of some fix that would work better, I'll be happy to hear of it!

Also, it took me quite a bit of digging through source code to find out how to create a FontSet and FontPolicy.  If there is more documentation, I'd be happy to hear of that as well.

**Comment by DevCharly** [comment]
Had the same problem in FlatLaf and was able to solve it by using
~~~java
Font font = new javax.swing.text.StyleContext().getFont( family, style, size );
~~~
to create fonts instead of `new Font(...)`.

This creates a composite font that is able to display all Unicode characters.

See commit https://github.com/JFormDesigner/FlatLaf/commit/9eaee8d2c4b7a6823328baccec1315e90384c940

Hope this helps.

**Comment by kirill-grouchnikov** [comment]
Thanks! Looks like you're only doing this on Windows?

**Comment by DevCharly** [comment]
No, on all platforms.

**Comment by kirill-grouchnikov** [comment]
Just verified that it works on Windows. The font fallback already works on my Mac machine, but I'll add it for all the platforms. Just need to figure out the right place to put it.

**Comment by enwired** [comment]
Thanks.  Glad this was fixed.
