### ISSUE TITLE
Inconsistent theming schemes with redundant coloring

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#403]
### Version of Radiance (latest development is 6.0-SNAPSHOT)
6.0-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)
Theming

### Version of Java (current minimum is 9)
JRE 17

### Version of OS
Windows 10

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
The radiance theming works like a charm, using radiance-sunshine version of Jan 2022. Thanks a lot!

However, after upgrading to the latest version (downloaded at 2022/08/23), it is found that there are inconsistent theming schemes with redundant coloring: 

  BusinessBlueSteelSkin, BusinessBlackSteelSkin, FieldOfWheatSkin, ...

With these skins, the coloring of image buttons,  as well as other components (JCheckBox, JButton, JComboBox, JRadioButton)
suddenly changes after some time at use. In all cases, the redundant coloring appears at the upper of these components.  
![coloring](https://user-images.githubusercontent.com/56999195/186123567-c0bcdd57-69c3-41d2-8da2-ed6314dac862.PNG)

**Comment by kirill-grouchnikov** [comment]
This looks like it's coming from the [new implementation](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/theming/src/main/java/org/pushingpixels/radiance/theming/api/painter/fill/StandardFillPainter.java#L124) of specular highlights. 

The [old one](https://github.com/kirill-grouchnikov/radiance/blob/c6d3c8e5302384a99dd425a9ff0557ecbcf03ae1/theming/src/main/java/org/pushingpixels/radiance/theming/api/painter/fill/StandardFillPainter.java#L91) was somewhat similar, using offscreen images for emulated visuals.

The main difference is that the old one used a combination of gradients and composites, and the new one (due to switch to direct rendering) is getting the underlying `WriteableRaster` and then setting pixels directly on it with `WriteableRaster.setDataElements`.

I'm not seeing anything that would require disposing of the buffered image or the writeable raster. The visuals also appear "correct" in terms of the harder specular highlight up top (the yellow part) and the fading of the enclosure (the red part). The only thing I can think of is that during the computation of the color channel values and the alpha, one or more of them either underflows (less than 0) or overflows (more than 255), and that overwrites some of the bits in the other channel(s).

I'll add the checks in that code, but other than that I don't have a good lead.

**Comment by kirill-grouchnikov** [comment]
Can you try the latest snapshot binaries? Not sure if the checks are going to help, but hopefully they do.

**Comment by goodwilling** [comment]
Thank you. I have tried the latest snapshot binaries but things seem not to change as anticipated.

**Comment by kirill-grouchnikov** [comment]
Do you still see the color issues? If yes, how long does it take to start happening? Does it depend on Java version, OS version, maybe graphics driver?

**Comment by goodwilling** [comment]
Thank you. I still see the color issues on Windows 10 (with NVidia Geforce GT 730). It can quickly happen if I roll the mouse on menus of JCheckBoxMenuItem. 
Following your suggestion, I have tried the latest snapshot binaries on Windows 11 (integrated Graphics card),  RedHat Linux 8, RedHat Linux 9 (inside VirtualBox).  No color issues are observed on these systems. 
On the other hand, I have tried to change the Java version from 17 to 11 on Windows 10, and the color issues are still seen. 
Therefore, the color issues seem to depend on OS version (maybe graphics driver),  but not Java version.

**Comment by kirill-grouchnikov** [comment]
I can explore a couple of alternatives. Would you be able to build a local version of Radiance from source, or would you need snapshot binaries to be uploaded to Sonatype?

**Comment by kirill-grouchnikov** [comment]
Please test the latest snapshot binaries from Sonatype

**Comment by goodwilling** [comment]
The color issues on Windows 10 are not seen using the latest snapshot binaries. Thanks!
 
In my case the jar files from Sonatype can not be downloaded (due to security check?) , so I compiled the source codes to get the snapshot binaries.

On the other hand, the following problems are found using the latest snapshot binaries:

(1) Vertical scrollbars will disappear if they are scrolled down.  Horizontal scrollbars are of no problem. 
(2) In my application an internal frame containing a customized slider can not be booted, although there is no problem in Windows/metal look and feel, as well as radiance theming of the version Jan-2022. 
(This internal frame can be booted using the latest snapshot binaries if the adding of customized slider is commented out.)

**Comment by kirill-grouchnikov** [comment]
Additional issues should be filed as separate entries, one for each bug. Closing this as fixed.
