### ISSUE TITLE
Feature: rotating in one icon class to render different icons

### ISSUE THREAD

**Issue by homebeaver** [kirill-grouchnikov/radiance#407]
Hi Kriill, this is my feature suggestion:

I use svg to generate icons. Sometimes it is not necessary to have many svgs. Look at the following example demo: 

![grafik](https://user-images.githubusercontent.com/3493126/188915154-681b07df-9c05-4d10-98fa-cb1aa1972e76.png)

- in CENTER there is the origin svg 
- the arrow shows the NORTH like the button above
- all the buttons around are generated from the same generated icon class

To implement this in radiance same changes are to be done.

What do you think about?
Regards EUGen

**Comment by kirill-grouchnikov** [comment]
I'd rather have this as a wrapper icon along the lines of what already exists in https://github.com/kirill-grouchnikov/radiance/tree/sunshine/component/src/main/java/org/pushingpixels/radiance/component/api/common/icon instead of baking this into every single transcoded icon which would result in bigger class files for everybody
