### ISSUE TITLE
[Theming] question on RadianceDefaultIconPack

### ISSUE THREAD

**Issue by homebeaver** [kirill-grouchnikov/radiance#417]
Hi @kirill-grouchnikov 

why do you use factory method `uiResourceOf` and sometimes `of`?

```java
...
    @Override
    public RadianceIcon getTextSelectAllActionIcon(int preferredSize,
            RadianceColorScheme preferredIconColorScheme) {
        RadianceIcon result = ic_select_all_black_24px.uiResourceOf(preferredSize, preferredSize);
        result.setColorFilter(color -> preferredIconColorScheme.getForegroundColor());
        return result;
    }

    @Override
    public RadianceIcon getColorChooserColorPalettesIcon(int preferredSize,
            RadianceColorScheme preferredIconColorScheme) {
        RadianceIcon result = ic_palette_black_24px.of(preferredSize, preferredSize);
        result.setColorFilter(color -> preferredIconColorScheme.getForegroundColor());
        return result;
    }

```
tkx in advance EUGen

**Comment by kirill-grouchnikov** [comment]
Great question. The context menu icons for text components and color chooser icons are all wrapped with the internal `BladeTransitionAwareIcon` which is used for icons that are set on components that support transitions - such as rollover effects on menus or buttons, for example. Essentially, these icons are not used statically, but rather every frame of that transition they are recomputed dynamically. 

That's not really strongly connected to the difference between `of` and `uiResourceOf`. You would want to use `uiResourceOf` in case of icons (or other resources such as colors, borders, etc) that should be replaced on any UI change such as skin change. So that's where `uiResourceOf` is used in the icon pack for things like option pane icons and others.

With all this, there should be no difference in switching all of these icon pack methods to use `uiResourceOf` for consistency on my side.
