### ISSUE TITLE
Radiance theming of SwingX components

### ISSUE THREAD

**Issue by msommer24** [kirill-grouchnikov/radiance#446]
I have a request: is it possible to add the possibility of radiance to SwingX components? Like before with Substance.
There is a current and stable fork of SwingX here: https://github.com/homebeaver/SwingSet3

**Comment by kirill-grouchnikov** [comment]
I don't have plans to do that in the core Radiance distribution. Substance indeed used to provide some support (see here for the [last source](https://github.com/kirill-grouchnikov/substance-swingx/commit/6ade92c11aa6c00fa36dd9315a93c2de76d46b06)).

SwingX development was discontinued in 2013 and effectively frozen in time since then. There were quite a few things that SwingX implementation did that did not play well with third-party look-and-feels, and at some point I lost interest in trying to support an abandoned component library.

Radiance [theming layer](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/theming/overview.md) has APIs for applying the Radiance visuals on third-party components, if anybody is willing to take on the task of providing Radiance visuals for SwingX - whichever fork of SwingX that happens to be.
