### ISSUE TITLE
FlatLaF compatability

### ISSUE THREAD

**Issue by tlf30** [kirill-grouchnikov/radiance#455]
Hello, 
I was wondering how compatible radiance was with FlatLaF.
I have a large application that we would like to add a ribbon bar to, but are heavily dependent on FlatLaF support. Many of our other third party libraries and our own components fully support FlatLaF and some external dependencies require it for the features we use. 

Are there any plans to support FlatLaF? I see in the documentation that the radiance components require the Radiance laf. For our use case, we would like to use the radiance components, but with any laf. 

Thank you,
Trevor

**Comment by kirill-grouchnikov** [comment]
I don't see myself taking on the task of providing FlatLaf support for any Radiance component out the box in the foreseeable future. A long time ago, Flamingo (the predecessor of Radiance components) did have rudimentary support for other LAFs, taking some entries from the `UIManager` table, and doing some renderer-inspired tricks to try and emulate the appearance of various elements under other look-and-feels. 

When Flamingo was folded into Radiance, I made a decision to remove that support. It didn't give pleasant visual results, and at that time (and since then) there was no interest expressed by any other look-and-feel libraries to support those components by using their own drawing / animation APIs - which is the right way to make this integration.

You can still see that old structure even today in the Radiance codebase, as I didn't really bother to clean that up:
* [internal/ui/ribbon](https://github.com/kirill-grouchnikov/radiance/tree/sunshine/component/src/main/java/org/pushingpixels/radiance/component/internal/ui/ribbon) for the basic layer
* [internal/theming/ribbon/ui](https://github.com/kirill-grouchnikov/radiance/tree/sunshine/component/src/main/java/org/pushingpixels/radiance/component/internal/theming/ribbon/ui) for Radiance-specific visuals

At the moment, those integration points are not supported as any sort of contract for other look-and-feels to rely on for proper integration - and they are all in the `internal` package to reflect that.

If there is any interest from the side of either the core FlatLaf library distribution, or from an interested third party like yourself to integrate Radiance components with the FlatLaf rendering and animation APIs, I will certainly consider moving the basic UI delegates into the supported API layer of Radiance, and work with that developer on refining the separation of basic logic on the Radiance side and providing the needed extension points to integrate LAF-specific logic that would work for both Radiance and FlatLaf.

Having said that, I will repeat again that I do not have any plans to provide such complete integration myself.

**Comment by kirill-grouchnikov** [comment]
Closing this, unless there is specific and committed interest to make Radiance components work with FlatLaf - or any other actively developed look-and-feel.
