### ISSUE TITLE
[Documentation / FAQ entry] Does radiance work with GraalVM or may it work eventually? e. g. static native image

### ISSUE THREAD

**Issue by rubyFeedback** [kirill-grouchnikov/radiance#491]
Does radiance work with GraalVM or may it work eventually? e. g. static native image.

I assume right now no; perhaps in the future?

Just curious. I had good results with GraalVM on Linux in general; not so much with
windows (last I checked static images are also not possible on windows; I am curious
whether radiance explored that option. I assume right now this is not possible, but
getting your thoughts in a sentence or two may be nice to have in the FAQ too.)

**Comment by kirill-grouchnikov** [comment]
There's nothing special about Radiance that I can think of that would make it work or not work with GraalVM. There is no native code in Radiance. Maybe something with reflection that might not work, and would need special handling? 

I haven't looked into this area in general, and no plans to look into it specifically for Radiance. If there is something in Radiance that is explicitly not working for GraalVM, file a specific bug, otherwise there's nothing actionable here.
