### ISSUE TITLE
[All] Fail the build when any deprecated API is used

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#86]
If this is not feasible for particular project(s), fail build selectively so that the codebase evolves and stays modern.

**Comment by kirill-grouchnikov** [comment]
There are no deprecation warnings building with Java 8 anymore. However, building with Java 9 shows a whole bunch of deprecated stuff that was marked as such starting in Java 9. Moving away from those APIs will be part of https://github.com/kirill-grouchnikov/radiance/issues/2

**Comment by kirill-grouchnikov** [comment]
And things like this can't even be fixed, since the deprecation in a later version of the platform is replaced with an API not available on older versions

/Users/kirillg/Projects/radiance/substance/src/main/java/org/pushingpixels/substance/internal/ui/SubstancePasswordFieldUI.java:176: warning: [deprecation] drawSelectedText(Graphics,int,int,int,int) in PlainView has been deprecated
        protected int drawSelectedText(Graphics g, final int x, final int y, int p0, int p1)
                      ^

**Comment by brunchboy** [comment]
Yes, the few times I have decided to address issues like that, I have had to implement two different versions of the relevant code, and choose the proper one based on Java version. Quite annoying, and the only reason I bothered was because the Max/MSP/Jitter multimedia programming environment, for which I offer a plugin version of my lighting control software, will never move beyond Java 6 on the Mac (they switched to JavaScript for extensions, and, well, I have a great many dependencies on Java libraries, including Java3D, so a rewrite in JavaScript is not going to happen.)
